version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:3.6
    ports:
      - "40917:27017"

  app:
    container_name: app
    env_file:
      - .env
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/src
    links:
      - mongo
    depends_on:
      - mongo